global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  # Мониторинг самого Prometheus
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Мониторинг приложения парсера
  - job_name: 'vseinstrumenti-parser'
    static_configs:
      - targets: ['vseinstrumenti-parser:8080']
    metrics_path: '/metrics'
    scrape_interval: 10s

  # Мониторинг OpenTelemetry Collector
  - job_name: 'otel-collector'
    static_configs:
      - targets: ['otel-collector:8889']
    scrape_interval: 10s

  # Мониторинг Redis
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
    metrics_path: '/metrics'
    scrape_interval: 10s

  # Мониторинг cAdvisor
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
    scrape_interval: 10s

  # Мониторинг Seq
  - job_name: 'seq'
    static_configs:
      - targets: ['seq:5341']
    scrape_interval: 30s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093